[llm]
provider = "gemini"
model = "gemini-flash-lite-latest"

[policy]
allow_risk = "low"
blocklist = [ "^wp db drop", "^wp user delete" ]

[runner]
default = "ssh"

[[hosts]]
name = "docker"
runner = "docker_compose"
api_url = "http://localhost:8080/wp-json"
api_username = "low2023"
api_password = "SPye aKZ7 4m3H hW63 7Svc RJGe"
# The [hosts.docker_compose] section is optional.
# Default service is 'wpcli' and path is '/var/www/html'.



[[hosts]]
name = "エナガブログ"
api_url = "https://low2023.com/wp-json"

[hosts.ssh]
host = "www315.conoha.ne.jp"
port = 8022
user = "c0688186"
key_path = "C:/Users/shima/.ssh/id_rsa"
strict_host_key_checking = false
wp_path = "/opt/alt/php81/usr/bin/php /home/c0688186/bin/wp"
wordpress_path = "/home/c0688186/public_html/low2023.com"