services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wp_data:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepassword
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db_data:/var/lib/mysql

  # SSH enabled container to simulate the target server environment
  ssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: wp_ssh_server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Tokyo
      - PASSWORD_ACCESS=true
      - USER_PASSWORD=password # For testing purposes
      - USER_NAME=kusanagi
    ports:
      - "2222:2222"
    volumes:
      - wp_data:/var/www/html # Mount the same volume as WordPress to access files
      - ./ssh_keys:/config/.ssh # For public key auth testing
    restart: unless-stopped

  
  wpcli:
    image: wordpress:cli
    depends_on:
      - wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepassword
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wp_data:/var/www/html

  caddy:
    image: caddy:2
    depends_on:
      - wordpress
    ports:
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    networks:
      - default
  
volumes:
  wp_data:
  db_data:
